### ISSUE TITLE
Usecase Diagram demo

### ISSUE THREAD

**Issue by Dacoband** [Dacoband/PRN212-WPF-HairSalonBookingApp#1]
Link tham khảo [thamkhảo](https://github.com/Qharny/Salon-booking-system)

**Comment by Dacoband** [comment]
[Usecase Diagram Demo](https://lucid.app/lucidchart/824dcfad-7d90-4208-b3dd-33fb6f480cf2/edit?viewport_loc=-978%2C-93%2C3326%2C1625%2C0_0&invitationId=inv_7c70a3c7-e214-4ccb-ab2f-1262ca8745fd)

Đây là usecase của tui với thức làm @kopami @phanvongocphu coi thử nhennnn 😍😍

**Comment by kopami** [comment]
[UCD Demo](https://lucid.app/lucidchart/207594e3-9f86-4a1b-98b9-2db15ab41921/edit?view_items=__Y_6gzl-0gY&invitationId=inv_053244d6-84b4-48ac-9ebb-fd517cf36c2a)
